spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/chat_db
    username: postgres
    password: postgres
  flyway:
    schemas:
      - public
  jpa:
    show-sql: true
  http:
    media-types:
      css: text/css


server:
  port: 8080